---
services:

  logstash:
    image: jahrik/arm-logstash:latest
    networks:
      - elk
    environment:
      ELASTICSEARCH_HOST: "${ELASTICSEARCH_HOST:-elasticsearch}"
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
      XPACK_MONITORING_ENABLED: "false"
    ports:
      - 5000:5000
      - 5000:5000/udp
      - 5044:5044

networks:
  elk:
    driver: overlay
    external: true
