version: '3'

services:

  logstash:
    image: jahrik/arm-logstash:arm32v7
    environment:
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL}"
    ports:
      - 5000:5000
      - 5044:5044
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm32v7
