input {
  tcp {
    port => 5000
  }
  udp {
    port => 5000
  }
  beats {
    port => 5044
  }
}
output {
  elasticsearch {
    hosts => "${ELASTICSEARCH_HOST:elasticsearch}:9200"
    manage_template => false
    index => "logstash-%{+YYYY.MM.dd}"
  }
}
